use_frameworks!

platform :ios, '12.0'

target 'NiViewIoT_Example' do
  pod 'NiViewIoT', :path => '../'

  target 'NiViewIoT_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
